=head1 Informal Coding Standards for I<tcsproxy>

=over 3

=item Compile with F<gcc -Wall -pedantic>.

=item No warnings allowed.  If they occur, put in a cast or whatever is
necessary to make the compiler happy.

=item Comment bountifully.  Header for each function should list at
least the following:

=over 5

=item Description of what function does

=item Description of inputs expected

=item Description of outputs returned

=item Whether the function is thread-safe

=item Description of logic, if applicable

=item B<Important:> Any assumptions made by the function (existence of a
global variable that has already been initialized, etc.)

=back

