#!/usr/sww/bin/perl

BEGIN { push(@INC,"/disks/barad-dur/now/pythia/release/lib/perl-5.002");
    }

use LWP;
$u = new LWP::UserAgent;

while(<>) {
    chomp;
    s#^/##;
    $fn = $& if /[\w\.-]+\.gif/;
    $url = "http://www.ibm.com/$_";
    warn "$url\n";
    $u->request(new HTTP::Request("GET",$url), "imgdir/$fn");
}




