#!/usr/bin/perl -w

$WIDTH = 6;
$ASC = 7;
$DESC = 1;
$HEIGHT = $ASC + $DESC;

$defrow = " " x (128*$WIDTH);
if (length($defrow) % 16) {
    $defrow .= " " x (16 - (length($defrow) % 16));
}
die unless (length($defrow) % 16 == 0);

@row = ($defrow) x $HEIGHT;

while(<>) {
    next unless /char \#(\d+)/;
    $cnum = $1;
    $wpos = $cnum * $WIDTH;
    $_ = <>;
    /Left:\s*(\d+)\s*Right:\s*(\d+)\s*Ascent:\s*(-?\d+)\s*Descent:\s*(-?\d+)/
	or die;
    ($left,$right,$asc,$desc) = ($1,$2,$3,$4);
    for $i (($ASC-$asc)..($ASC+$desc-1)) {
	$_ = <>;
	chomp;
	s/-/ /g;
	substr($row[$i],$wpos+$left,$right-$left) = $_;
    }
}

$total = '';
for $i (0 .. $#row) {
    $rev = $row[$i];
    $rev =~ tr/ #/# /;
    $total .= $row[$i] . $rev;
}
$total =~ tr/ #/01/;
$data = pack('B*', $total);

print $data;
